server:
  port: 8443
  error:
    whitelabel:
      enabled: false
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/example.p12
    key-store-password: P@ssw0rd
    key-alias: example
    enabled: true
